<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="alphabot">
    <!-- Start GZ or Ignition depending on ROS 2 Version -->
    <xacro:arg name="is_ignition" default="true"/>

    <!-- Load Simulated or Real Hardware Interfaces -->
    <xacro:arg name="is_sim" default="true"/>


    <xacro:include filename="$(find alphabot_description)/urdf/alphabot_gazebo.xacro"/> 
    <xacro:include filename="$(find alphabot_description)/urdf/alphabot_ros2_control.xacro"/>  
    <!-- <xacro:include filename="$(find alphabot_description)/urdf/depth_camera.xacro" /> -->

    <xacro:property name="wheel_radius" value="0.034" />
    <xacro:property name="wheel_width" value="0.012" />
    <xacro:property name="robot_height" value="0.116" />
    <xacro:property name="robot_width" value="0.256" />
    <xacro:property name="wheel_depth" value="0.256" />
    <xacro:property name="caster_wheel" value="0.01468" />


    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="silver">
        <color rgba="0.79 0.82 0.93 1"/>
    </material>
    <material name="dark_grey">
        <color rgba="0.3 0.3 0.3 1"/>
    </material>

    <link name="base_footprint"/>

    <link name="base_link">
        <inertial>
            <mass value="2.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.06" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.256 0.256 0.116"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.15" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.256 0.256 0.116"/>
            </geometry>
        </collision>
    </link>

    <link name="wheel_left_link">
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.2"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>    
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>    
        </collision>
    </link>  

    <link name="wheel_right_link">
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.02"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>    
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>    
        </collision>
    </link>  

    <link name="caster_front_link">
        <inertial>
            <mass value="0.05"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel}"/>
            </geometry>
        </collision>
    </link>

    <link name="caster_rear_link">
        <inertial>
            <mass value="0.05"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel}"/>
            </geometry>
        </collision>
    </link>

    <!-- Define the joints -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${caster_wheel}" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="0.060 -0.105 0.02" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="0.060 0.105 0.02" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="caster_front_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_front_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="-0.08 -0.08 0.0" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <joint name="caster_rear_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_rear_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="-0.08 0.08 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <link name="laser_link">
    <inertial>
      <origin xyz="-0.011945780406062 -0.000381929217680526 -0.0170649378129477" rpy="0 0 0" />
      <mass value="0.073084435549317" />
      <inertia ixx="1.96074931730795E-05" ixy="-3.62091076640009E-07" ixz="4.28230084046735E-07"
               iyy="2.40983835136327E-05" iyz="1.50180909250652E-08"
               izz="4.14184164228595E-05" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.08 0.08 0.03" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.08 0.08 0.03" />
      </geometry>
    </collision>
  </link>

  <link name="imu_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.005 0.005 0.005"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.005 0.005 0.005"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00000015" ixy="0" ixz="0" iyy="0.00000015" iyz="0" izz="0.00000015" />
        </inertial>
    </link>

  <joint name="laser_joint" type="fixed">
    <origin xyz="-0.065 0.0 ${robot_height + 0.005}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="laser_link" />
    <axis xyz="0 0 0" />
  </joint>

  <joint name="imu_joint" type="fixed">
    <origin xyz="-0.0 0.0 0.0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
    <axis xyz="0 0 0" />
  </joint>


</robot>